notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - oicr:S9k4EowgQv9AnbCfEZHSzCsg
sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
install:
- docker version
- pip2.7 install --user cwl-runner cwltool==1.0.20160323212343 schema-salad==1.7.20160316203940 avro==1.7.7
- docker pull commonworkflowlanguage/nodejs-engine
before_script:
- psql -c "create user dockstore with password 'dockstore' createdb;" -U postgres
- psql -c "ALTER USER dockstore WITH superuser;" -U postgres
- psql -c 'create database webservice_test with owner = dockstore;' -U postgres
- export PATH=$PATH:$PWD/dockstore-client/target
script: mvn -B clean install -DskipITs=false -Pconfidential-tests
# cobertura does not seem to properly work with multiple module projects or java 8 at the moment
# after_success:
# - mvn -B clean -DskipITs=false cobertura:cobertura cobertura:cobertura-integration-test coveralls:report
before_install:
- openssl aes-256-cbc -K $encrypted_b6cd6518e9f3_key -iv $encrypted_b6cd6518e9f3_iv
  -in dockstore-integration-testing/src/test/resources/secrets.tar.enc -out dockstore-integration-testing/src/test/resources/secrets.tar -d
- tar xvf dockstore-integration-testing/src/test/resources/secrets.tar
